In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max.columns", None)

# Inflation trends en Latin America (2000-2025)
## Proyect Objetive: Analyze inflation across select Latin America countries between 2000-2025.
### Note: Argentina and Venezuela were excluded from first part because World Bank Data regarding the indicador for these countries is limited

## Business questions:
1. Which country experienced the hights average inflation?
2. Which country maintained the greatest price stability?
3. Which country exhibited the hights inflation volaty?
4. How did inflation evolve across the region?
5. How does Latin America compare with the United States ?

In [23]:
# Cargar datos
inflation_clean=pd.read_csv("../data/processed/inflation_latam_clean.cvs")

inflation_clean.head(10)

  country  year  inflation
0  Brasil  2025   5.016753
1  Brasil  2024   4.367464
2  Brasil  2023   4.593563
3  Brasil  2022   9.280106
4  Brasil  2021   8.301660
5  Brasil  2020   3.211768
6  Brasil  2019   3.732976
7  Brasil  2018   3.664850
8  Brasil  2017   3.446373
9  Brasil  2016   8.739144

In [24]:
#Validaciones iniciales

inflation_clean.shape

(233, 3)

In [25]:
inflation_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    233 non-null    str
 1   year       233 non-null    int64
 2   inflation  233 non-null    float64
dtypes: float64(1), int64(1), str(1)
memory usage: 5.6 KB

In [26]:
inflation_clean.describe()

              year   inflation
count   233.000000  233.000000
mean   2012.446352    5.318873
std       7.487225    6.997223
min    2000.000000   -0.355546
25%    2006.000000    2.826171
50%    2012.000000    4.116338
75%    2019.000000    6.597185
max    2025.000000   96.096376

In [27]:
#question 1
avg_inflation=(
    inflation_clean.groupby("country")["inflation"].mean().sort_values(ascending=False)
)

avg_inflation

country
ECUADOR          8.137016
URUGUAY          8.004431
Brasil           6.227091
PARAGUAY         5.894837
Colombia         5.373229
Mexico           4.722731
Chile            3.791243
Peru             3.037406
United States    2.576392
Name: inflation, dtype: float64

## Finding 1
Countries are ranked according to their average inflation rate during the analysis period. Ecuador is the country with the highest average inflation during the 2000–2025 period (8.13%), Uruguay followed closely with an average inflation rate of 8.00%. whereas the United States was the country with the lowest average inflation (2.57%). 

Overall, the results indicate that Latin American economies experienced persistently higher inflation rates than the United States during the period analyzed.

In [41]:
#question 2
inflation_stability=(
    inflation_clean
    .groupby("country")["inflation"]
    .std()
    .sort_values()
)
inflation_stability

country
Mexico            1.509400
United States     1.627764
Peru              1.730979
Chile             2.387718
Colombia          2.509816
Brasil            2.520291
URUGUAY           3.123781
PARAGUAY          3.153656
ECUADOR          19.385252
Name: inflation, dtype: float64

#Finding 2
Price stability was evaluated using the standard deviation of annual inflation rates. Although Mexico shows greater stability based on the standard deviation results, it is important to note that its average inflation rate during the study period was the second highest. These findings indicate that Mexico's inflation neither improved nor worsened during the period, remaining at an annual average of 4.72%; it is therefore advisable to evaluate inflation on a year-by-year basis to obtain more precise data regarding the policies implemented.

In [42]:
#question 3. País más volatil 
inflation_volatility=(
    inflation_clean
    .groupby("country")["inflation"]
    .std()
    .sort_values(ascending=False)
)

inflation_volatility

country
ECUADOR          19.385252
PARAGUAY          3.153656
URUGUAY           3.123781
Brasil            2.520291
Colombia          2.509816
Chile             2.387718
Peru              1.730979
United States     1.627764
Mexico            1.509400
Name: inflation, dtype: float64

In [52]:
inflation_clean[
    inflation_clean["country"]=="ECUADOR"
].sort_values("inflation", ascending=False)

     country  year  inflation
103  ECUADOR  2000  96.096376
102  ECUADOR  2001  37.676745
101  ECUADOR  2002  12.483598
95   ECUADOR  2008   8.400096
100  ECUADOR  2003   7.929365
94   ECUADOR  2009   5.159968
91   ECUADOR  2012   5.101722
92   ECUADOR  2011   4.474533
88   ECUADOR  2015   3.966646
89   ECUADOR  2014   3.589220
93   ECUADOR  2010   3.554377
81   ECUADOR  2022   3.466170
97   ECUADOR  2006   3.298748
99   ECUADOR  2004   2.743232
90   ECUADOR  2013   2.721776
96   ECUADOR  2007   2.276185
80   ECUADOR  2023   2.215688
98   ECUADOR  2005   2.168277
87   ECUADOR  2016   1.728265
79   ECUADOR  2024   1.547325
78   ECUADOR  2025   0.710469
86   ECUADOR  2017   0.417336
84   ECUADOR  2019   0.266013
82   ECUADOR  2021   0.133251
85   ECUADOR  2018  -0.224103
83   ECUADOR  2020  -0.338872

# Finding 3
Inflation volatility was measured using the standard deviation of annual inflation rates. Ecuador was the most volatile and also showed the highest average inflation during the period. This result was strongly influenced by the exceptionally high inflation rate observed in 2000 (96.09%), as well as episodes of negative inflation recorded in later years.

 as might have been expected from the previous result, the least volatile country was Mexico.

These observations reflect genuine macroeconomic conditions and were therefore retained in the dataset.

In [30]:
#question 4
regional_avg = (
inflation_clean
.groupby("year")["inflation"]
.mean()
.reset_index()
)
regional_avg.head()

   year  inflation
0  2000  16.286764
1  2001   8.761131
2  2002   6.785253
3  2003   8.364128
4  2004   4.534241

In [31]:
regional_avg.describe()

              year  inflation
count    26.000000  26.000000
mean   2012.500000   5.311692
std       7.648529   2.801675
min    2000.000000   2.955753
25%    2006.250000   3.587628
50%    2012.500000   4.492362
75%    2018.750000   5.620311
max    2025.000000  16.286764

In [54]:
#Mostrar años de mayor inflación regional
regional_avg.sort_values(
"inflation",
ascending=False
).head(10)

    year  inflation
0   2000  16.286764
1   2001   8.761131
22  2022   8.630011
3   2003   8.364128
8   2008   6.952629
2   2002   6.785253
23  2023   5.858653
11  2011   4.905285
21  2021   4.849907
16  2016   4.792641

In [61]:
inflation_clean[
    inflation_clean["year"]==2022
].sort_values(
    by="inflation",
    ascending=False
)

           country  year  inflation
29           Chile  2022  11.643867
55        Colombia  2022  10.177231
133       PARAGUAY  2022   9.765567
3           Brasil  2022   9.280106
185        URUGUAY  2022   9.104380
159           Peru  2022   8.333706
210  United States  2022   8.002800
107         Mexico  2022   7.896276
81         ECUADOR  2022   3.466170

# Finding 4 
Post-Pandemic Inflation Surge
 
Regional inflation accelerated significantly between 2021 and 2022, increasing from 4.85% to 8.63%.
 
Although inflation moderated in 2023, average price growth remained above pre-pandemic levels, suggesting persistent inflationary pressures across the region.

Notably, the United States also experienced elevated inflation (8.00%), suggesting that the inflationary episode was driven by global factors rather than country-specific conditions alone.
 
These results indicate that inflationary pressures following the COVID-19 pandemic affected both Latin American economies and advanced economies alike.

In [43]:
#Tabla de inflacion de Latam
latam = (
inflation_clean[
inflation_clean["country"] != "United States"
]
.groupby("year")["inflation"]
.mean()
.reset_index()
)

latam.rename(
columns={"inflation": "latam_inflation"},
inplace=True
)

In [44]:
#Tabla de EEUU

usa = (
inflation_clean[
inflation_clean["country"] == "United States"
][["year", "inflation"]]
)

usa.rename(
columns={"inflation": "usa_inflation"},
inplace=True
)

In [45]:
comparison = latam.merge(
usa,
on="year"
)

comparison.head()

   year  latam_inflation  usa_inflation
0  2000        17.900503       3.376857
1  2001         9.503000       2.826171
2  2002         7.435156       1.586032
3  2003         9.125882       2.270095
4  2004         4.766366       2.677237

In [46]:
#DIFERENCIA DE LA INFLACION DE LATAM Y EEUU
comparison["gap"] = (
comparison["latam_inflation"]
- comparison["usa_inflation"]
)

comparison.head()

   year  latam_inflation  usa_inflation        gap
0  2000        17.900503       3.376857  14.523646
1  2001         9.503000       2.826171   6.676829
2  2002         7.435156       1.586032   5.849124
3  2003         9.125882       2.270095   6.855787
4  2004         4.766366       2.677237   2.089129

In [47]:
avg_inflation

country
ECUADOR          8.137016
URUGUAY          8.004431
Brasil           6.227091
PARAGUAY         5.894837
Colombia         5.373229
Mexico           4.722731
Chile            3.791243
Peru             3.037406
United States    2.576392
Name: inflation, dtype: float64

In [48]:
inflation_volatility

country
ECUADOR          19.385252
PARAGUAY          3.153656
URUGUAY           3.123781
Brasil            2.520291
Colombia          2.509816
Chile             2.387718
Peru              1.730979
United States     1.627764
Mexico            1.509400
Name: inflation, dtype: float64

In [51]:
inflation_clean["year"].min()

np.int64(2000)

In [53]:
inflation_clean.groupby("country")["inflation"].agg(
["min", "max", "mean", "std"]
).sort_values("std", ascending=False)

                    min        max      mean        std
country
ECUADOR       -0.338872  96.096376  8.137016  19.385252
PARAGUAY       1.767516  14.236797  5.894837   3.153656
URUGUAY        4.359341  19.379730  8.004431   3.123781
Brasil         3.211768  14.714920  6.227091   2.520291
Colombia       2.016992  11.735904  5.373229   2.509816
Chile          0.353045  11.643867  3.791243   2.387718
Peru           0.193135   8.333706  3.037406   1.730979
United States -0.355546   8.002800  2.576392   1.627764
Mexico         2.720641   9.491561  4.722731   1.509400

In [60]:
country_summary=(
    inflation_clean
    .groupby("country")["inflation"]
    .agg(["mean","std","min","max"])
).round(2)

country_summary

               mean    std   min    max
country
Brasil         6.23   2.52  3.21  14.71
Chile          3.79   2.39  0.35  11.64
Colombia       5.37   2.51  2.02  11.74
ECUADOR        8.14  19.39 -0.34  96.10
Mexico         4.72   1.51  2.72   9.49
PARAGUAY       5.89   3.15  1.77  14.24
Peru           3.04   1.73  0.19   8.33
URUGUAY        8.00   3.12  4.36  19.38
United States  2.58   1.63 -0.36   8.00

In [62]:
country_summary.sort_values(
by="mean",
ascending=False
)

               mean    std   min    max
country
ECUADOR        8.14  19.39 -0.34  96.10
URUGUAY        8.00   3.12  4.36  19.38
Brasil         6.23   2.52  3.21  14.71
PARAGUAY       5.89   3.15  1.77  14.24
Colombia       5.37   2.51  2.02  11.74
Mexico         4.72   1.51  2.72   9.49
Chile          3.79   2.39  0.35  11.64
Peru           3.04   1.73  0.19   8.33
United States  2.58   1.63 -0.36   8.00

In [63]:
country_summary.sort_values(
by="std",
ascending=False
)

               mean    std   min    max
country
ECUADOR        8.14  19.39 -0.34  96.10
PARAGUAY       5.89   3.15  1.77  14.24
URUGUAY        8.00   3.12  4.36  19.38
Brasil         6.23   2.52  3.21  14.71
Colombia       5.37   2.51  2.02  11.74
Chile          3.79   2.39  0.35  11.64
Peru           3.04   1.73  0.19   8.33
United States  2.58   1.63 -0.36   8.00
Mexico         4.72   1.51  2.72   9.49